### ISSUE TITLE
Crash when running (v2.8.0)

### ISSUE THREAD

**Issue by mikakaraila** [node-opcua/node-opcua-pki#19]
C:\DNA\PlantViewer\node_modules\node-opcua-pki>node bin\crypto_create_CA.js demo --dev
```javascript
internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:/Users/ADMINI~1/AppData/Local/Temp/2/empty_config.cnf'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1362:35)
    at execute_openssl (C:\DNA\PlantViewer\node_modules\node-opcua-pki\dist\pki\toolbox.js:193:12)
    at C:\DNA\PlantViewer\node_modules\node-opcua-pki\dist\pki\toolbox.js:168:13
    at C:\DNA\PlantViewer\node_modules\node-opcua-pki\dist\pki\toolbox.js:65:9
    at C:\DNA\PlantViewer\node_modules\node-opcua-pki\dist\misc\install_prerequisite.js:349:13
    at C:\DNA\PlantViewer\node_modules\node-opcua-pki\dist\misc\install_prerequisite.js:319:20
    at C:\DNA\PlantViewer\node_modules\node-opcua-pki\dist\misc\install_prerequisite.js:173:21
    at C:\DNA\PlantViewer\node_modules\node-opcua-pki\dist\misc\install_prerequisite.js:69:9
    at ChildProcess.exithandler (child_process.js:294:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:/Users/ADMINI~1/AppData/Local/Temp/2/empty_config.cnf'
}

C:\DNA\PlantViewer\node_modules\node-opcua-pki>
```

**Comment by mikakaraila** [comment]
I expect it will / should download and install openssl, but fails as crash above shows.

Actually openssl is already installed:
![image](https://user-images.githubusercontent.com/5184524/108976663-6a8e2200-7690-11eb-9a64-f1a798560382.png)

**Comment by mikakaraila** [comment]
It was missing folder 2 from local temp? As I created it program started to work.

![image](https://user-images.githubusercontent.com/5184524/108977052-d5d7f400-7690-11eb-9819-1c3ce99516c3.png)

**Comment by erossignon** [comment]
OK, let close then

**Comment by sukkamehu** [comment]
Faced the same issue after couple of months successful operation causing application to crash. I'm on version 2.43.0.

@erossignon could library try to create folder if not existing somewhere in line #229 of toolbox.ts https://github.com/node-opcua/node-opcua-pki/blob/b23b8190dd68f56fe31c9940ca5a27f5c4ed730d/lib/pki/toolbox.ts#L229
![image](https://user-images.githubusercontent.com/13398758/139639406-fa12dc0f-0358-488e-b130-b418036ee460.png)
