### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by bompi88** [node-opcua/node-opcua-pki#2]
https://github.com/node-opcua/node-opcua-pki/blob/c99391f3f82c422531f89fe6bbbe1f7c38227912/lib/misc/install_prerequisite.js#L119

Seems like the case where you have `LOCALAPPDATA` environment variable declared, and the directory `Programs` does not exists, the `get_openssl_folder_win32` returns undefined. Implementations of `get_openssl_folder_win32` should probably be in the lines of:

```js
    function get_openssl_folder_win32() {
        if (process.env.LOCALAPPDATA) {
            var user_program_folder = path.join(process.env.LOCALAPPDATA, "Programs");
            if (fs.existsSync(user_program_folder)) {
                return path.join(user_program_folder, "openssl");
            }
        } 
        return path.join(process.cwd(), "openssl");
    }
``` 

Added PR #3

**Comment by bompi88** [comment]
@erossignon Does this make sense?

**Comment by erossignon** [comment]
Yes!  sorry for the late reply,
