### ISSUE TITLE
Postinstall error: response 404 during post install to download Openssl.exe (64bit win). Broken url. Easy fix. (version 1.0.2)

### ISSUE THREAD

**Issue by CostantinoSpano** [node-opcua/node-opcua-pki#39]
Hi,

the link to download openssl.exe (64bit win) give 404 during postinstall. There is only a digit wrong in the url to fix it.

### 64bit url
From this (wrong last digit 7 of 1886617):
https://github.com/node-opcua/node-opcua-pki/files/1886617/openssl-1.0.2o-x64_86-win64.zip

to this (correct last digit 8 of 1886618):
https://github.com/node-opcua/node-opcua-pki/files/1886618/openssl-1.0.2o-x64_86-win64.zip

### 32bit url
No problem

Here the file and lines:
https://github.com/node-opcua/node-opcua-pki/blob/9bb63324cbb14d545b47a1d5959206e1df07bc17/lib/misc/install_prerequisite.ts#L230C1-L232C2

I need this specific version for a legacy project

**Comment by erossignon** [comment]
Node-opcua-pki 1.02 is deprecated and no longer maintained. Please upgrade to the latest version.
